# Generated by Django 4.1.4 on 2023-01-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_app_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
